# Generated by Django 2.1.7 on 2019-04-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
